	nios_system2 u0 (
		.audio_clk_out_clk                         (<connected-to-audio_clk_out_clk>),                         //                       audio_clk_out.clk
		.audio_config_external_interface_SDAT      (<connected-to-audio_config_external_interface_SDAT>),      //     audio_config_external_interface.SDAT
		.audio_config_external_interface_SCLK      (<connected-to-audio_config_external_interface_SCLK>),      //                                    .SCLK
		.audio_external_interface_ADCDAT           (<connected-to-audio_external_interface_ADCDAT>),           //            audio_external_interface.ADCDAT
		.audio_external_interface_ADCLRCK          (<connected-to-audio_external_interface_ADCLRCK>),          //                                    .ADCLRCK
		.audio_external_interface_BCLK             (<connected-to-audio_external_interface_BCLK>),             //                                    .BCLK
		.audio_external_interface_DACDAT           (<connected-to-audio_external_interface_DACDAT>),           //                                    .DACDAT
		.audio_external_interface_DACLRCK          (<connected-to-audio_external_interface_DACLRCK>),          //                                    .DACLRCK
		.clk_50_2_in_clk                           (<connected-to-clk_50_2_in_clk>),                           //                         clk_50_2_in.clk
		.clk_50_3_in_clk                           (<connected-to-clk_50_3_in_clk>),                           //                         clk_50_3_in.clk
		.clk_50_in_clk                             (<connected-to-clk_50_in_clk>),                             //                           clk_50_in.clk
		.hex2_hex0_external_interface_HEX0         (<connected-to-hex2_hex0_external_interface_HEX0>),         //        hex2_hex0_external_interface.HEX0
		.hex2_hex0_external_interface_HEX1         (<connected-to-hex2_hex0_external_interface_HEX1>),         //                                    .HEX1
		.hex2_hex0_external_interface_HEX2         (<connected-to-hex2_hex0_external_interface_HEX2>),         //                                    .HEX2
		.hex5_hex3_external_interface_HEX0         (<connected-to-hex5_hex3_external_interface_HEX0>),         //        hex5_hex3_external_interface.HEX0
		.hex5_hex3_external_interface_HEX1         (<connected-to-hex5_hex3_external_interface_HEX1>),         //                                    .HEX1
		.hex5_hex3_external_interface_HEX2         (<connected-to-hex5_hex3_external_interface_HEX2>),         //                                    .HEX2
		.mtl_clk_out_clk                           (<connected-to-mtl_clk_out_clk>),                           //                         mtl_clk_out.clk
		.parallel_port_0_external_interface_export (<connected-to-parallel_port_0_external_interface_export>), //  parallel_port_0_external_interface.export
		.parallel_port_1_external_interface_export (<connected-to-parallel_port_1_external_interface_export>), //  parallel_port_1_external_interface.export
		.ps2_0_external_interface_CLK              (<connected-to-ps2_0_external_interface_CLK>),              //            ps2_0_external_interface.CLK
		.ps2_0_external_interface_DAT              (<connected-to-ps2_0_external_interface_DAT>),              //                                    .DAT
		.ps2_mouse_external_interface_CLK          (<connected-to-ps2_mouse_external_interface_CLK>),          //        ps2_mouse_external_interface.CLK
		.ps2_mouse_external_interface_DAT          (<connected-to-ps2_mouse_external_interface_DAT>),          //                                    .DAT
		.red_leds_external_interface_export        (<connected-to-red_leds_external_interface_export>),        //         red_leds_external_interface.export
		.reset_bridge_in_reset_n                   (<connected-to-reset_bridge_in_reset_n>),                   //                     reset_bridge_in.reset_n
		.sdram_clk_out_clk                         (<connected-to-sdram_clk_out_clk>),                         //                       sdram_clk_out.clk
		.sdram_wire_addr                           (<connected-to-sdram_wire_addr>),                           //                          sdram_wire.addr
		.sdram_wire_ba                             (<connected-to-sdram_wire_ba>),                             //                                    .ba
		.sdram_wire_cas_n                          (<connected-to-sdram_wire_cas_n>),                          //                                    .cas_n
		.sdram_wire_cke                            (<connected-to-sdram_wire_cke>),                            //                                    .cke
		.sdram_wire_cs_n                           (<connected-to-sdram_wire_cs_n>),                           //                                    .cs_n
		.sdram_wire_dq                             (<connected-to-sdram_wire_dq>),                             //                                    .dq
		.sdram_wire_dqm                            (<connected-to-sdram_wire_dqm>),                            //                                    .dqm
		.sdram_wire_ras_n                          (<connected-to-sdram_wire_ras_n>),                          //                                    .ras_n
		.sdram_wire_we_n                           (<connected-to-sdram_wire_we_n>),                           //                                    .we_n
		.sys_clk_out_clk                           (<connected-to-sys_clk_out_clk>),                           //                         sys_clk_out.clk
		.vga_clk_out_clk                           (<connected-to-vga_clk_out_clk>),                           //                         vga_clk_out.clk
		.video_controller_external_interface_CLK   (<connected-to-video_controller_external_interface_CLK>),   // video_controller_external_interface.CLK
		.video_controller_external_interface_HS    (<connected-to-video_controller_external_interface_HS>),    //                                    .HS
		.video_controller_external_interface_VS    (<connected-to-video_controller_external_interface_VS>),    //                                    .VS
		.video_controller_external_interface_BLANK (<connected-to-video_controller_external_interface_BLANK>), //                                    .BLANK
		.video_controller_external_interface_SYNC  (<connected-to-video_controller_external_interface_SYNC>),  //                                    .SYNC
		.video_controller_external_interface_R     (<connected-to-video_controller_external_interface_R>),     //                                    .R
		.video_controller_external_interface_G     (<connected-to-video_controller_external_interface_G>),     //                                    .G
		.video_controller_external_interface_B     (<connected-to-video_controller_external_interface_B>)      //                                    .B
	);

